version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python -m flask --app app.main:flask_app run --host=0.0.0.0 --port=8000"
    environment:
      - FLASK_DEBUG=1
      - FLASK_ENV=development